version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    hostname: nginx-hostname
    restart: always
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - ./ssl/server.crt:/etc/nginx/certs/server.crt
      - ./ssl/server.key:/etc/nginx/certs/server.key
      - ./volume-files/default-separated-by-port.conf:/etc/nginx/conf.d/default.conf
      - ./volume-files/index-http.html:/usr/share/nginx/html/index-http.html
      - ./volume-files/index-https.html:/usr/share/nginx/html/index-https.html
